using System;

namespace AutotaskNET.Entities
{
    /// <summary>
    /// This entity describes information and results for surveys generated by Autotask.
    /// </summary>
    /// <seealso cref="AutotaskNET.Entities.Entity" />
    public class SurveyResults : Entity
    {
        #region Properties

        public override bool CanCreate => false;
        public override bool CanUpdate => false;
        public override bool CanQuery => true;
        public override bool CanDelete => false;
        public override bool CanHaveUDFs => false;

        #endregion //Properties

        #region Constructors

        public SurveyResults() : base() { } //end SurveyResults()
        public SurveyResults(net.autotask.webservices.SurveyResults entity) : base(entity)
        {

        } //end SurveyResults(net.autotask.webservices.SurveyResults entity)

        public static implicit operator net.autotask.webservices.SurveyResults(SurveyResults surveyresults)
        {
            return new net.autotask.webservices.SurveyResults()
            {
                id = surveyresults.id,

            };

        } //end implicit operator net.autotask.webservices.SurveyResults(SurveyResults surveyresults)

        #endregion //Constructors

        #region Fields

        #region ReadOnly Fields

        public int? AccountID; //ReadOnly [Account]
        public decimal CompanyRating; //ReadOnly
        public int? ContactID; //ReadOnly [Contact]
        public decimal ContactRating; //ReadOnly
        public DateTime? CompleteDate; //ReadOnly
        public decimal ResourceRating; //ReadOnly
        public DateTime? SendDate; //ReadOnly
        public decimal SurveyRating; //ReadOnly
        public int? TicketID; //ReadOnly [Ticket]

        #endregion //ReadOnly Fields

        #region ReadOnly Required Fields

        public int SurveyID; //ReadOnly Required [Survey]

        #endregion //ReadOnly Required Fields

        #endregion //Fields

    } //end SurveyResults

}
