using System;

namespace AutotaskNET.Entities
{
    /// <summary>
    /// This entity describes general information for a survey generated by Autotask.
    /// </summary>
    /// <seealso cref="AutotaskNET.Entities.Entity" />
    public class Survey : Entity
    {
        public override bool CanCreate => false;
        public override bool CanUpdate => false;
        public override bool CanQuery => true;
        public override bool CanDelete => false;
        public override bool CanHaveUDFs => false;

        #region ReadOnly Fields

        public string DisplayName { get; set; } //ReadOnly Length:100
        public string Description { get; set; } //ReadOnly Length:1000

        #endregion //ReadOnly Fields

        #region ReadOnly Required Fields

        public string Name { get; set; } //ReadOnly Required Length:100

        #endregion //ReadOnly Required Fields
        
    } //end Survey

}
